FROM virtimus/ths:devMachine

#USER ths

RUN echo "uniq2" && cd /tmp && wget https://github.com/virtimus/makaronLab/releases/download/0.0.1/makaronLab.tar.gz \
    && tar -xvf makaronLab.tar.gz && cd makaronLab

#USER root
